# Generated by Django 4.0.7 on 2023-07-15 01:53

from django.db import migrations

network_id = 1
network_name = "Ethereum Goerli"

contract_name = "WalletBalanceProvider"
contract_address = "0xe0bb4593f74B804B9aBd9a2Ec6C71663cEE64E29"
abi = [{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"address","name":"token","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address[]","name":"users","type":"address[]"},{"internalType":"address[]","name":"tokens","type":"address[]"}],"name":"batchBalanceOf","outputs":[{"internalType":"uint256[]","name":"","type":"uint256[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"provider","type":"address"},{"internalType":"address","name":"user","type":"address"}],"name":"getUserWalletBalances","outputs":[{"internalType":"address[]","name":"","type":"address[]"},{"internalType":"uint256[]","name":"","type":"uint256[]"}],"stateMutability":"view","type":"function"},{"stateMutability":"payable","type":"receive"}]

def add_new_network(apps, schema):
    Network = apps.get_model("tracker", "Network")
    Network.objects.update_or_create(
        id=network_id, defaults=dict(name=network_name)
    )


def remove_network(apps, schema):
    Network = apps.get_model("tracker", "Network")
    Network.objects.get(id=network_id).delete()


def add_new_contract(apps, schema):
    Contract = apps.get_model("tracker", "Contract")
    Contract.objects.update_or_create(
        name=contract_name, address=contract_address, network_id=network_id, abi=abi
    )

def remove_contract(apps, schema):
    Contract = apps.get_model("tracker", "Contract")
    Contract.objects.get(name=contract_name, address=contract_address).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_contract_address_contract_name_and_more'),
    ]

    operations = [
        migrations.RunPython(add_new_network, remove_network, elidable=False),
        migrations.RunPython(add_new_contract, remove_contract, elidable=False),
    ]
