# Generated by Django 4.0.7 on 2023-09-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20230716_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_factor', models.TextField()),
                ('total_eth_collateral', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.contract')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.network')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
