# Generated by Django 4.0.7 on 2023-09-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.contract'),
        ),
        migrations.AlterField(
            model_name='position',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.network'),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.network')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('network', 'address')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.wallet'),
        ),
    ]
