# Generated by Django 4.0.7 on 2023-09-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_wallet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='total_eth_collateral',
            new_name='total_usd_collateral',
        ),
    ]
